language: php

dist: trusty

php:
  - 7.3
  - 7.4snapshot

matrix:
  allow_failures:
    - php: 7.4snapshot

before_script:
  - composer install --prefer-dist --no-interaction --no-progress
  - composer update #required to install zend-servicemanager and zend-barcode

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
